### PR TITLE
[WIP] socket.io server-side setup

### PR DESCRIPTION
**Pull request by lina**
- added dependencies in bower.json and package.json (preemptive setup for client-side socket.io)
- made changes to index.html and index.js to connect to socket.io

### CODE REVIEW

**Comment by lina** [comment]
I'll mark this as in progress when I'm on a computer again. Don't merge yet

**Comment by codydaig** [comment]
@linalu1 Are you planning on integrating with the database?

**Comment by lina** [comment]
Progress update:
- Currently a group chat module is added. This will be converted to private chat function for each user
- There currently isn't a separate file for socketio inside lib folder. Refactoring out io module from index.js seems a little redundant for now and I spend more time figuring out how to refactor than work on the code. Will do this later
- Rebased my branch 6:30pm Friday and resolved minor conflicts in bower.json, package.json and index.html

**Comment by linalu1** [comment]
changes are included in pull request #93

**Comment by lina** [comment]
changes are included in pull request #93

**Pull request closed without merging**
