### PR TITLE
updated master and postlist controllers 

### PR DESCRIPTION
**Pull request by Kevbyte**
master-ctrl now can broadcast data to postlist-ctrl

this is to facilitate search results populating the postlist view

### CODE REVIEW

**Comment by codydaig** [comment]
@Kevbyte The CI test failed. Can you check why and fix?

**Comment by Kevbyte** [comment]
Fixed issues. Please review and merge when ready.

**Comment by AndrewKishino** [comment]
lgtm

**Comment by codydaig** [comment]
LGTM. 

@Kevbyte Have you tested the search yet, or is there still a server side error?

**Comment by Kevbyte** [comment]
Still getting errors. See gitter.

**Comment by Kevbyte** [comment]
I have successfully incorporated image upload and retrieval. I want to clean up the code a bit before I submit a pull request. I'll do that tonight. 

Cody, have you taken a look at what's going on with search on the server side?

**Comment by lina** [comment]
lgtm

**Pull request merged**
